### ISSUE TITLE
Weird vertical layout 

### ISSUE THREAD

**Issue by calintat** [sd-visualiser/sd-visualiser#67]
Import thunks.sd.

Before:
<img src="https://github.com/sdvisualiser/sd-visualiser/assets/16837293/046ec23f-772d-484b-b15c-6eedbcf0607c" alt="before" width="500" height="500">

After:
<img src="https://github.com/sdvisualiser/sd-visualiser/assets/16837293/e7a9781a-b5a5-4d2c-8244-8d5845279cef)" alt="after" width="500" height="500">

**Comment by alexarice** [comment]
I'm not sure how you can set the constraints such that this doesn't happen
