### ISSUE TITLE
Web deployment shows up as blank

### ISSUE THREAD

**Issue by keorn** [sd-visualiser/sd-visualiser#90]
![image](https://github.com/user-attachments/assets/e9edc12b-781e-49dd-96b0-ab4c128d8bcf)

Accessing https://sd-visualiser.github.io/sd-visualiser/ from Chrome. I would guess that some actions should be available within the editor.

**Comment by alexarice** [comment]
Does clicking in the black panel and typing not bring up text?

**Comment by keorn** [comment]
Aha, I see, I was just confused by the blankness of it, thanks. I guess with https://github.com/sd-visualiser/sd-visualiser/issues/50 it will be more obvious. You may still consider adding some placeholder text especially given that people may not know any of the available languages, e.g. github does it like this:
![image](https://github.com/user-attachments/assets/3b6ce8ba-14eb-4283-b01f-e5b65436dfba)

**Comment by alexarice** [comment]
I have added the hint text in commit https://github.com/sd-visualiser/sd-visualiser/commit/38129b442f3e5811278e772aaa9c18679180d85a . If this passes ci it should be testable online
